import * as stylex from "@stylexjs/stylex";
import { colors, fonts } from "../ui/theme.stylex";

export const nodeStyles = stylex.create({
  wrap: {
    position: "absolute",
    transform: "translate(-50%, -50%)",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
  },
  wrapSelected: {
    zIndex: 4,
  },
  card: {
    width: 168,
    backgroundColor: colors.white,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.faint,
    padding: "10px 12px 11px",
    cursor: "pointer",
    color: colors.ink,
    fontFamily: fonts.mono,
    boxSizing: "border-box",
    userSelect: "none",
    textAlign: "left",
  },
  selected: {
    borderColor: colors.lime,
    outlineWidth: 1,
    outlineStyle: "solid",
    outlineColor: colors.lime,
    outlineOffset: 2,
  },
  stopped: {
    borderColor: colors.coral,
    opacity: 0.78,
  },
  leader: {
    backgroundColor: colors.paleLime,
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: colors.lime,
  },
  candidate: {
    borderColor: colors.lime,
  },
  stale: {
    backgroundColor: colors.paleCoral,
    borderLeftWidth: 3,
    borderLeftStyle: "solid",
    borderLeftColor: colors.coral,
  },
  informed: {
    backgroundColor: colors.paleLime,
  },
  flashing: {
    outlineWidth: 1,
    outlineStyle: "solid",
    outlineColor: colors.lime,
    outlineOffset: 3,
  },
  header: {
    display: "flex",
    alignItems: "baseline",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 6,
  },
  id: {
    fontSize: 15,
    fontWeight: 700,
    letterSpacing: "0.06em",
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  status: {
    fontSize: 10,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    color: colors.muted,
  },
  statusDown: {
    color: colors.coral,
  },
  dot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    backgroundColor: colors.lime,
    flexShrink: 0,
  },
  dotStopped: {
    backgroundColor: colors.coral,
  },
  role: {
    fontSize: 12,
    fontWeight: 600,
    letterSpacing: "0.08em",
    marginBottom: 2,
  },
  line: {
    fontSize: 12,
    lineHeight: 1.4,
    color: colors.ink,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  muted: {
    color: colors.muted,
  },
  timer: {
    marginTop: 8,
  },
  timerMeta: {
    display: "flex",
    justifyContent: "space-between",
    fontSize: 10,
    color: colors.muted,
    marginBottom: 4,
    letterSpacing: "0.04em",
  },
  timerTrack: {
    height: 5,
    backgroundColor: colors.faint,
    overflow: "hidden",
  },
  timerFill: {
    height: "100%",
    backgroundColor: colors.lime,
  },
  timerUrgent: {
    backgroundColor: colors.coral,
  },
  flash: {
    fontFamily: fonts.mono,
    fontSize: 10,
    color: colors.lime,
    letterSpacing: "0.04em",
    maxWidth: 168,
    textAlign: "center",
    lineHeight: 1.35,
  },
  actions: {
    display: "flex",
    gap: 6,
  },
  action: {
    backgroundColor: colors.lime,
    color: colors.charcoal,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.lime,
    fontFamily: fonts.mono,
    fontSize: 11,
    padding: "4px 9px",
    cursor: "pointer",
    fontWeight: 600,
  },
  danger: {
    backgroundColor: "transparent",
    color: colors.coral,
    borderWidth: 1,
    borderStyle: "solid",
    borderColor: colors.coral,
    fontFamily: fonts.mono,
    fontSize: 11,
    padding: "4px 9px",
    cursor: "pointer",
  },
});
